// Actions liées aux étudiants
export const studentsconstant = {
    FETCH_STUDENTS_REQUEST : 'FETCH_STUDENTS_REQUEST',
    FETCH_STUDENTS_SUCCESS : 'FETCH_STUDENTS_SUCCESS',
    FETCH_STUDENTS_FAILURE : 'FETCH_STUDENTS_FAILURE',
}

export const addstudent = {
    ADD_STUDENTS_REQUEST : 'ADD_STUDENTS_REQUEST',
    ADD_STUDENTS_SUCCESS : 'ADD_STUDENTS_SUCCESS',
    ADD_STUDENTS_FAILURE : 'ADD_STUDENTS_FAILURE',
}
 
export const updatestudent = {
    UPDATE_STUDENTS_REQUEST : 'UPDATE_STUDENTS_REQUEST',
    UPDATE_STUDENTS_SUCCESS  :'UPDATE_STUDENTS_SUCCESS',
    UPDATE_STUDENTS_FAILURE :'UPDATE_STUDENTS_FAILURE',
}

export const deletestudent = {
    DELETE_STUDENTS_REQUEST : 'DELETE_STUDENTS_REQUEST',
    DELETE_STUDENTS_SUCCESS : 'DELETE_STUDENTS_SUCCESS',
    DELETE_STUDENTS_FAILURE : 'DELETE_STUDENTS_FAILURE',
}

export const updatestudentstatus = {
    UPDATE_STUDENTS_STATUS_REQUEST : 'UPDATE_STUDENTS_STATUS_REQUEST',
    UPDATE_STUDENTS_STATUS_SUCCESS : 'UPDATE_STUDENTS_STATUS_SUCCESS',
    UPDATE_STUDENTS_STATUS_FAILURE : 'UPDATE_STUDENTS_STATUS_FAILURE',
}

// Actions liées aux professeurs
export const professorConstants = {
    FETCH_PROFESSORS_REQUEST : 'FETCH_PROFESSORS_REQUEST',
    FETCH_PROFESSORS_SUCCESS : 'FETCH_PROFESSORS_SUCCESS',
    FETCH_PROFESSORS_FAILURE : 'FETCH_PROFESSORS_FAILURE',
}
 
export const addprofessor = {
    ADD_PROFESSORS_REQUEST : 'ADD_PROFESSORS_REQUEST',
    ADD_PROFESSORS_SUCCESS : 'ADD_PROFESSORS_SUCCESS',
    ADD_PROFESSORS_FAILURE : 'ADD_PROFESSORS_FAILURE',
}

export const updateprof = {
    UPDATE_PROFESSORS_REQUEST : 'UPDATE_PROFESSORS_REQUEST',
    UPDATE_PROFESSORS_SUCCESS : 'UPDATE_PROFESSORS_SUCCESS',
    UPDATE_PROFESSORS_FAILURE : 'UPDATE_PROFESSORS_FAILURE',
}

export const deleteprofs = {
    DELETE_PROFESSORS_REQUEST : 'DELETE_PROFESSORS_REQUEST',
    DELETE_PROFESSORS_SUCCESS : 'DELETE_PROFESSORS_SUCCESS',
    DELETE_PROFESSORS_FAILURE : 'DELETE_PROFESSORS_FAILURE',
}
